version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./database/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      - PRODUCTION=
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: client
    environment:
      - NODE_ENV="production"
    volumes:
      - .:/code
    ports:
      - "3000:5000"
    depends_on:
      - backend
